### ISSUE TITLE
Change map style

### ISSUE THREAD

**Issue by israelst** [NAMD/SegPub#27]
We may use [this tool](http://gmaps-samples-v3.googlecode.com/svn/trunk/styledmaps/wizard/index.html) to personalize the map

**Comment by fccoelho** [comment]
Looks interesting
Em 07/04/2015 10:45, "Israel Teixeira" <notifications@github.com> escreveu:

**Comment by israelst** [comment]
Interesting tool to compare different map tile styles: http://mc.bbbike.org/mc/

**Comment by israelst** [comment]
As we have changed the style to CartoDB Positron, I'm closing this issue.
